/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microconrollerserialport;

/**
 * İşime yarayacak linkler -- serial port communication in java
 * https://www.programmersought.com/article/92356352325/
 * https://www.codeproject.com/Questions/450480/How-communicate-with-serial-port-in-Java
 * http://www.java2s.com/Code/Java/Development-Class/ReadfromaSerialportnotifyingwhendataarrives.htm
 * https://blog.henrypoon.com/blog/2011/01/01/serial-communication-in-java-with-example-program/
 * https://www.java-samples.com/showtutorial.php?tutorialid=11
 * @author MERT
 */
public class Frm_SerialPort extends javax.swing.JPanel {

    /**
     * Creates new form Frm_SerialPort
     */
    public Frm_SerialPort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
